-- MySQL Script generated by MySQL Workbench
-- 05/03/17 16:00:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema real_state
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `client` ;

CREATE TABLE IF NOT EXISTS `client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `email` VARCHAR(45) NULL,
  `telphone` VARCHAR(45) NULL,
  `observation` LONGTEXT NULL,
  `ic_contact` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin` ;

CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(80) NULL,
  `pass` LONGTEXT NULL,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

insert into admin values(NULL,'admin','admin',1);

-- -----------------------------------------------------
-- Table `plant_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plant_request` ;

CREATE TABLE IF NOT EXISTS `plant_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` TEXT NULL,
  `plant_link` TEXT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `ci_sessions` (
        `id` varchar(128) NOT NULL,
        `ip_address` varchar(45) NOT NULL,
        `timestamp` int(10) unsigned DEFAULT 0 NOT NULL,
        `data` blob NOT NULL,
        KEY `ci_sessions_timestamp` (`timestamp`)
);


-- -----------------------------------------------------
-- Table `contact_form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contact_form` ;

CREATE TABLE IF NOT EXISTS `contact_form` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` TEXT NULL,
  `name` VARCHAR(80) NULL,
  `message` LONGTEXT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `admin` (`username`, `pass`, `active`) VALUES ('admin', 'admin', '1');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- MySQL Script generated by MySQL Workbench
-- 05/03/17 16:00:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema real_state
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `client` ;

CREATE TABLE IF NOT EXISTS `client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `email` VARCHAR(45) NULL,
  `telphone` VARCHAR(45) NULL,
  `observation` LONGTEXT NULL,
  `ic_contact` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin` ;

CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(80) NULL,
  `pass` LONGTEXT NULL,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

insert into admin values(NULL,'admin','admin',1);

-- -----------------------------------------------------
-- Table `plant_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plant_request` ;

CREATE TABLE IF NOT EXISTS `plant_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` TEXT NULL,
  `plant_link` TEXT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `ci_sessions` (
        `id` varchar(128) NOT NULL,
        `ip_address` varchar(45) NOT NULL,
        `timestamp` int(10) unsigned DEFAULT 0 NOT NULL,
        `data` blob NOT NULL,
        KEY `ci_sessions_timestamp` (`timestamp`)
);


-- -----------------------------------------------------
-- Table `contact_form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contact_form` ;

CREATE TABLE IF NOT EXISTS `contact_form` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` TEXT NULL,
  `name` VARCHAR(80) NULL,
  `message` LONGTEXT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `admin` (`username`, `pass`, `active`) VALUES ('admin', 'admin', '1');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- MySQL Script generated by MySQL Workbench
-- 05/03/17 16:00:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema real_state
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `client` ;

CREATE TABLE IF NOT EXISTS `client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `email` VARCHAR(45) NULL,
  `telphone` VARCHAR(45) NULL,
  `observation` LONGTEXT NULL,
  `ic_contact` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin` ;

CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(80) NULL,
  `pass` LONGTEXT NULL,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

insert into admin values(NULL,'admin','admin',1);

-- -----------------------------------------------------
-- Table `plant_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plant_request` ;

CREATE TABLE IF NOT EXISTS `plant_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` TEXT NULL,
  `plant_link` TEXT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `ci_sessions` (
        `id` varchar(128) NOT NULL,
        `ip_address` varchar(45) NOT NULL,
        `timestamp` int(10) unsigned DEFAULT 0 NOT NULL,
        `data` blob NOT NULL,
        KEY `ci_sessions_timestamp` (`timestamp`)
);


-- -----------------------------------------------------
-- Table `contact_form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contact_form` ;

CREATE TABLE IF NOT EXISTS `contact_form` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` TEXT NULL,
  `name` VARCHAR(80) NULL,
  `message` LONGTEXT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `admin` (`username`, `pass`, `active`) VALUES ('admin', 'admin', '1');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
